apiVersion: 1

datasources:
  # source: https://github.com/grafana/grafana/blob/main/docs/sources/datasources/prometheus/_index.md
  - name: Prometheus
    type: prometheus
    uid: prometheus-ds
    url: http://prometheus:9090
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo-ds
          name: traceID
          urlDisplayLabel: 'View Trace'
